---
version: 2.1

orbs:
  node: circleci/node@5.0.0

workflows:
  version: 2
  build:
    jobs:
      - node/run:
          npm-run: 'lint'
          version: '14.19'
      - node/test:
          requires:
            - node/run
          run-command: 'test:cover'
          test-results-path: reports
          version: '14.19'
