---
version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0
  node: circleci/node@5.0.0

workflows:
  version: 2
  build:
    jobs:
      - node/run:
          npm-run: 'lint'
          version: '14.19'
      - node/test:
          requires:
            - node/run
          run-command: 'test:cover'
          test-results-path: reports
          version: '14.19'
      - cypress/run:
          requires:
            - node/test
          config: baseUrl=http://localhost:4321
          executor: cypress/base-14
          start: npm run e2e:app
          store_artifacts: true
          wait-on: http-get://localhost:4321
