---
version: 2.1

orbs:
  cypress: cypress-io/cypress@1.29.0
  node: circleci/node@5.0.0

jobs:
  storybook:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          node-version: "14.19"
      - node/install-packages
      - run:
          name: Install gh-pages
          command: |
            npm install --global gh-pages
            git config user.email 'build@circleci.com'
            git config user.name 'CircleCI Build'
      - run:
          name: Build Storybook site
          command: npm run storybook:build
      - store_artifacts:
          path: storybook-static
      - add_ssh_keys:
          fingerprints:
            - "c2:d3:12:f2:fc:99:7b:49:61:56:98:22:1c:7c:32:15"
      - run:
          name: Deploy to GitHub Pages
          command: gh-pages --message "[skip ci] Deploy Storybook" --dist storybook-static

workflows:
  version: 2
  build:
    jobs:
      - node/run:
          npm-run: "lint"
          version: "14.19"
      - node/test:
          requires:
            - node/run
          run-command: "test:cover"
          test-results-path: reports
          version: "14.19"
      - cypress/run:
          requires:
            - node/test
          config: baseUrl=http://localhost:4321
          executor: cypress/base-14
          no-workspace: true
          post-install:
            - run: apt update && apt install jq -y
          start: npm run e2e:app
          store_artifacts: true
          wait-on: http-get://localhost:4321
      - storybook:
          requires:
            - cypress/run
          filters:
            branches:
              only: main
